# Generated by Django 6.0.6 on 2026-06-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=230)),
                ('description', models.CharField(blank=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
